# Site settings
title: Deen Salehs portfolio web page
description: get in contact to get this
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: DEEN SALEH
user_description: On thing I like about myself is that i get the job done so want something like this get in touch and will work things thorugh.
user_title: Software Developer
email: salehudeen@gmail.com.com
twitter_username: @deensaleh1
github_username:  salehudeen
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
